apiVersion: v1
kind: Service
metadata:
  name: animals-api-service
  labels:
    app: animals-api
spec:
  type: NodePort
  selector:
    app: animals-api
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
    name: http